### ISSUE TITLE
Issues with total_playtime.lua

### ISSUE THREAD

**Issue by Tensai-Otaku** [oltodosel/mpv-scripts#1]
I am unable to get the following script to work. I have already installed FFmpeg and it's functioning through CMD and everything. I would really like the ability to be able to see the total duration of my playlist and was wondering if you could lend me a hand, so I can use it. I've already tried pasting the script into my script folder to no avail. I have tried several bindings too. My system is running Windows 10 if that's any help. Thank you in advance. Looking forward to hearing from you.

**Comment by oltodosel** [comment]
Edit this line to your config path. https://github.com/oltodosel/mpv-scripts/blob/7663d558da748d63eca7eaef484e915354cfe7fd/total_playtime.lua#L8

**Comment by Tensai-Otaku** [comment]
Thank you for fast reply. I tried to link it to my path as intended for windows but it didn't work. Here is the log

PS C:\Users\tayya> mpv C:\Users\tayya\AppData\Roaming\mpv\scripts\total_playtime.lua
Invalid value for option audio-display: attachment
Valid values are:
    no
    embedded-first
    external-first
Error parsing option audio-display (option parameter could not be parsed)
C:\Users\tayya\AppData\Roaming/mpv/mpv.conf:50: setting option audio-display='attachment' failed.
Option vf-remove: item label @ivtc not found.
Option vf-remove: item label @deinterlace not found.
Option vf-remove: item label @warpsharp not found.
Option vf-remove: item label @warpsharp not found.
Option vf-remove: item label @warpsharp_legacy not found.
Option vf-remove: item label @frameinfo not found.
Option vf-remove: item label @simulcast not found.
   cplayer: Can't load unknown script: C:\Users\tayya\AppData\Roaming/mpv/scripts/reload.lua.bak
   cplayer: Cannot find main.* for any supported scripting backend in: C:\Users\tayya\AppData\Roaming/mpv/scripts/Deletetotal_playtime:
total_playtime: stack traceback:
total_playtime:         [C]: at 0x7ff7bac815f0
   autosub:
   autosub: stack traceback:
   autosub:     [C]: at 0x7ff7bac815f0
total_playtime: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:8: invalid escape sequence near ''C:'
   autosub: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/au..."]:6: invalid escape sequence near ''C:'auto_profiles: Applying auto profile: nonsimulcast-autoprofile
   cplayer: Option vf-remove: item label @simulcast not found.
   cplayer: Failed to recognize file format.
   cplayer:
timelogger:
timelogger: stack traceback:
timelogger:     mp.defaults:510: in function 'call_event_handlers'
timelogger:     mp.defaults:555: in function 'dispatch_events'
timelogger:     mp.defaults:503: in function <mp.defaults:502>
timelogger:     [C]: at 0x7ff7bac83400
timelogger:     [C]: at 0x7ff7bac815f0
   cplayer: Exiting... (Errors when loading file)
timelogger: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/ti..."]:64: attempt to perform arithmetic on global 'totaltime' (a nil value)
toggle_pip:
toggle_pip: stack traceback:
toggle_pip:     [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:37: in function 'restore_properties'
toggle_pip:     [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:27: in function 'handler'
toggle_pip:     mp.defaults:510: in function 'call_event_handlers'
toggle_pip:     mp.defaults:555: in function 'dispatch_events'
toggle_pip:     mp.defaults:503: in function <mp.defaults:502>
toggle_pip:     [C]: at 0x7ff7bac83400
toggle_pip:     [C]: at 0x7ff7bac815f0
toggle_pip: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:37: bad argument #2 to 'set_property' (string expected, got nil)

**Comment by oltodosel** [comment]
> total_playtime: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:8: invalid escape sequence near ''C:'

You somehow messed up with editing the config at line 8. Copy it here.

**Comment by Tensai-Otaku** [comment]
Here you go. This is the line you wanted?
saved_probed_filename = "C:\Users\tayya\AppData\Roaming\mpv\scripts\total_playtime.list"

**Comment by oltodosel** [comment]
Double all back slashes in the path: \ -> \\\

**Comment by Tensai-Otaku** [comment]
I did that just now:  saved_probed_filename = "C:\\Users\\tayya\\AppData\Roaming\\mpv\\scripts\total_playtime.list". Is this right? Sadly, it didn't work. I pasted in the new log

PS C:\Users\tayya> mpv C:\Users\tayya\AppData\Roaming\mpv\scripts\total_playtime.lua
Option vf-remove: item label @ivtc not found.
Option vf-remove: item label @deinterlace not found.
Option vf-remove: item label @warpsharp not found.
Option vf-remove: item label @warpsharp not found.
Option vf-remove: item label @warpsharp_legacy not found.
Option vf-remove: item label @frameinfo not found.
Option vf-remove: item label @simulcast not found.
   autosub:
   autosub: stack traceback:
   autosub:     [C]: at 0x7ff7bac815f0
   autosub: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/au..."]:6: invalid escape sequence near ''C:'
total_playtime:
total_playtime: stack traceback:
total_playtime:         [C]: at 0x7ff7bac815f0
total_playtime: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:8: invalid escape sequence near '"C:\Users\tayya\AppData'
auto_profiles: Applying auto profile: nonsimulcast-autoprofile
   cplayer: Option vf-remove: item label @simulcast not found.
   cplayer: Failed to recognize file format.
timelogger:
timelogger: stack traceback:
timelogger:     mp.defaults:510: in function 'call_event_handlers'
timelogger:     mp.defaults:555: in function 'dispatch_events'
timelogger:     mp.defaults:503: in function <mp.defaults:502>
timelogger:     [C]: at 0x7ff7bac83400
timelogger:     [C]: at 0x7ff7bac815f0
   cplayer:
   cplayer: Exiting... (Errors when loading file)
timelogger: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/ti..."]:64: attempt to perform arithmetic on global 'totaltime' (a nil value)
toggle_pip:
toggle_pip: stack traceback:
toggle_pip:     [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:37: in function 'restore_properties'
toggle_pip:     [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:27: in function 'handler'
toggle_pip:     mp.defaults:510: in function 'call_event_handlers'
toggle_pip:     mp.defaults:555: in function 'dispatch_events'
toggle_pip:     mp.defaults:503: in function <mp.defaults:502>
toggle_pip:     [C]: at 0x7ff7bac83400
toggle_pip:     [C]: at 0x7ff7bac815f0
toggle_pip: Lua error: [string "C:\Users\tayya\AppData\Roaming/mpv/scripts/to..."]:37: bad argument #2 to 'set_property' (string expected, got nil)

**Comment by oltodosel** [comment]
I've no idea then.

Redownload the script anew, I've just made a small change.
Then switch `save_probed = true` to `save_probed = false`
This way the script will not save anything, but should be able to calculate time nonetheless.

**Comment by Tensai-Otaku** [comment]
I was able to do it now. I had to set the os.getenv(''APPDATA) for it to be able to calculate and log it. Thank you for your help. Its working now
