### ISSUE TITLE
[Fix] for windows users

### ISSUE THREAD

**Issue by Rickyrvxlovet** [oltodosel/mpv-scripts#13]
When i press F12 it says. F12 is not mapped

**Comment by oltodosel** [comment]
See if there are any errors before that. There should be, otherwise the script would work.

**Comment by oltodosel** [comment]
[[saved_probed_filename = '~/.config/mpv/scripts/total_playtime.list'](https://github.com/oltodosel/mpv-scripts/blob/8fe23a2ed32f64edeb8a3690def122c3dab60583/total_playtime.lua#L8)](https://github.com/oltodosel/mpv-scripts/blob/8fe23a2ed32f64edeb8a3690def122c3dab60583/total_playtime.lua#L8)

Change this line to windows-like appropriate path.
