### ISSUE TITLE
Making the calculation a bit more silent?

### ISSUE THREAD

**Issue by Kayizoku** [oltodosel/mpv-scripts#3]
It's a bit annoying to see the CMD prompts popup one after another, would it be possible to do the calculation in the background as you are watching something or hide the CMD prompts?

**Comment by oltodosel** [comment]
Be more specific.

**Comment by Kayizoku** [comment]
Ah, I see. Do you know what it could be?

**Comment by oltodosel** [comment]
I gather you're using `windows`? If so, then there's nothing you can do.
https://stackoverflow.com/questions/6362841/use-lua-os-execute-in-windows-to-launch-a-program-with-out-a-flash-of-cmd/6365296#6365296

**Comment by Kayizoku** [comment]
> I gather you're using `windows`? If so, then there's nothing you can do. https://stackoverflow.com/questions/6362841/use-lua-os-execute-in-windows-to-launch-a-program-with-out-a-flash-of-cmd/6365296#6365296

I see worth a shot. Thank you for clarifying.
