### ISSUE TITLE
Anyway to recalculate if a new entry is added in playlist?

### ISSUE THREAD

**Issue by Kayizoku** [oltodosel/mpv-scripts#4]
I want the script to recalculate again if a new entry is added into the playlist. It would also be neat if it calculated two playlist separately and not add on to the already calculated one. So my hope is it resets the value if you remove current playlist and replace it with a new one. I hope I am making sense.

**Comment by oltodosel** [comment]
Not with the current code. It's under MIT, so you're free to fork it however you'd like.

>my hope is it resets the value if you remove current playlist and replace it with a new one

For that you can disable saving duration of already probed files - change [this](https://github.com/oltodosel/mpv-scripts/blob/1eaca61a81a1fecf5f475e467dbad583459fb4ac/total_playtime.lua#L7) to `false`.

**Comment by Kayizoku** [comment]
> 

Could you please show me where I need to change save_probed to false in the total_time function to get this effect, if its no problem?

**Comment by oltodosel** [comment]
I literally linked the exact line - № 7.

**Comment by Kayizoku** [comment]
Oh, it's just that? I want it to remember the calculated parts, but recalculate again if a new entry is added to the playlist. I am new to Lua, so still don't understand how to accomplish this. If there's anyway, i'd appreciate if you told me

**Comment by oltodosel** [comment]
No, there's no way without writing the actual code to do the thing you want. Which I am not willing to do.

**Comment by Kayizoku** [comment]
> No, there's no way without writing the actual code to do the thing you want. Which I am not willing to do.

It shouldn't be that difficult, but I am still figuring out Lua. So could you describe what I have to do, so I can try to implement it myself? No hard feelings if you cannot. Thanks in advance.

**Comment by oltodosel** [comment]
No.
