### ISSUE TITLE
Show_Chapter: Automatically display the chapter when it changes and turns off after X seconds. -Request

### ISSUE THREAD

**Issue by Cananbolt** [oltodosel/mpv-scripts#5]
I was wondering if there was a way for the script to display automatically if the video changes chapter and for it to turn off after X seconds. I tried to do this by adding another line to the script 

mp.observe_property("chapter", nil, show_chapters)

however, this only activates the script at the start of the video. I'd like a way for the script to activate anytime a chapter changes. I also would like to know if there is a way for the script message to turn off after X seconds

**Comment by oltodosel** [comment]
I'm not going to do it.
