### ISSUE TITLE
[FR] total_playtime | Adjust playlist total playtime based on playback speed

### ISSUE THREAD

**Issue by xfzv** [oltodosel/mpv-scripts#6]
Just like `show_chapters`?

https://github.com/oltodosel/mpv-scripts/blob/1eaca61a81a1fecf5f475e467dbad583459fb4ac/show_chapters.lua#L2

**Comment by oltodosel** [comment]
Funnily enough, I had this implemented ages ago. Just forgot to update the script on github.
