### ISSUE TITLE
[Question / `total_playtime.lua`] What do these two functions do exactly?

### ISSUE THREAD

**Issue by xfzv** [oltodosel/mpv-scripts#7]
I was configuring my keybindings and noticed that `KP4` was calling `total_playtime.lua`. After a quick research:

https://github.com/oltodosel/mpv-scripts/blob/6edaf5d36a81f5469152f27bd3f513ebab9d6189/total_playtime.lua#L174-L175

I never noticed these keybindings before.

Could you please explain what these two functions do? All I see is that when pressing `KP4`, the current time changes when pressing `F12` again, but I'm not sure what the new value means. Let's say I'm at `00:04:26/05:56:00` on the second video of a 15 videos playlist, I press `KP4` and now the OSD shows `00:50:58/05:56:00`. :thinking:

When pressing `Shift+KP4`, it returns to the very beginning of the playlist but I'm not seeing anything different when pressing `F12`.

https://github.com/oltodosel/mpv-scripts/blob/6edaf5d36a81f5469152f27bd3f513ebab9d6189/total_playtime.lua#L124-L126
https://github.com/oltodosel/mpv-scripts/blob/6edaf5d36a81f5469152f27bd3f513ebab9d6189/total_playtime.lua#L129-L172

**Comment by oltodosel** [comment]
Those functions are not related to getting total time of the playlist.

The first one sorts the playlist by duration from low to high and back when pressed multiple times.
The second one sorts and then forces `mpv` to jump to the first entry of the playlist.
