### ISSUE TITLE
attempt to index global 'file' (a nil value)

### ISSUE THREAD

**Issue by Ruslang** [oltodosel/mpv-scripts#9]
1. Download and install latest mpv on Windows.
2. Download and install latest `total_playtime.lua` script. and fix path.
3. Run `mpv .` in folder with mkv files.
4. Hit F12 and q

I got the error below:
```
(Paused) AV: 00:00:07 / 00:00:20 (39%) A-V:  0.000
[total_playtime]
[total_playtime] stack traceback:
[total_playtime]        mp.defaults:230: in function 'fn'
[total_playtime]        mp.defaults:65: in function 'handler'
[total_playtime]        mp.defaults:380: in function 'handler'
[total_playtime]        mp.defaults:510: in function 'call_event_handlers'
[total_playtime]        mp.defaults:552: in function 'dispatch_events'
[total_playtime]        mp.defaults:503: in function <mp.defaults:502>
[total_playtime]        [C]: at 0x013fdc96b0
[total_playtime]        [C]: at 0x013fdc7d90
[total_playtime] Lua error: ...rs\Ruslan\AppData\Roaming/mpv/scripts/total_playtime.lua:69: attempt to index global 'file' (a nil value)
```

I expected osd msg with duration or smth like that.

Please help to fix it.

**Comment by oltodosel** [comment]
Your path [here](https://github.com/oltodosel/mpv-scripts/blob/8fe23a2ed32f64edeb8a3690def122c3dab60583/total_playtime.lua#L8) is at fault. Correct it.
Alternatively turn off saving probbed values [here](https://github.com/oltodosel/mpv-scripts/blob/8fe23a2ed32f64edeb8a3690def122c3dab60583/total_playtime.lua#L7) by setting it to `false`.

Слава Україні!
